development:
  secret_key_base: 'a4eb8fb39ccd57ba2f84a351189bf09c61d96dfbb8b2260c22f04508d0fa8ce1566ba31bcf2bfe2457914a9e5c242d7b331aa31dca8297a1469593e4c2c75fb8'
  aws_access_key: "AKIAIG6XYGOQHO373UAQ"
  aws_secret_key: "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"
  email_username: "paginaweb@pierco.com.co"
  email_password: "P13rc0w3b"
  aws_bucket: "piercodevelopment"
 
test:
  secret_key_base: 'a4eb8fb39ccd57ba2f84a351189bf09c61d96dfbb8b2260c22f04508d0fa8ce1566ba31bcf2bfe2457914a9e5c242d7b331aa31dca8297a1469593e4c2c75fb8'
  aws_access_key: "AKIAIG6XYGOQHO373UAQ"
  aws_secret_key: "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"
  email_username: "paginaweb@pierco.com.co"
  email_password: "P13rc0w3b"
  aws_bucket: "piercodevelopment"
 
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["aws_access_key"] %>
  aws_secret_key: <%= ENV["aws_secret_key"] %>
  email_username: <%= ENV["paginaweb@pierco.com.co"] %>
  email_password: <%= ENV["P13rc0w3b"] %>
  aws_bucket: <%= ENV["aws_bucket"] %>
  