development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
 
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
 
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  