# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

c = Company.new(name: "Pierco", address_1: "Calle 68 No. 50 - 18", city: "Barranquilla", stat: "Atlantico", postal_code: "00000", country: "Colombia", telephone_1: "3458123", email: "pierco@pierco.com", latitude: 10.9909, longitude: -74.8046 )
c.save
d = Distributor.new(company: Company.first, name: "Pierco", address_1: "Calle 68 No. 50 - 18", city: "Barranquilla", state: "Atlantico", postal_code: "00000", country: "Colombia", telephone_1: "3458123", email: "pierco@pierco.com.co", latitude: 10.9909, longitude: -74.8046)
d.save
c.default_distributor = d
c.save
Supplier.create({name: "Maxxis", address_1: "8th Fl, World Trade Building", address_2: "50, Sec. 1 Shin-Sheng S. Rd", city: "Taipei",  country: "Taiwan", company: c})
Supplier.create({name: "MOMO", address_1: "Via Winckelmann 2", city: "Milano", postal_code: "20146", country: "Italia", company: c})
ProductCategory.create({name: "Llantas Automóvil", description: "Llantas Automóvil", length: true, width: true, maximum_pressure: true, maximum_weight: true, color: false, diameter: true, part_number: true, service_description: true, lateral_wall: true, rim_width_range: true, tred_depth: true, company: c})  
ProductCategory.create({name: "Llantas Camioneta", description: "Llantas Camioneta", length: true, width: true, maximum_pressure: true, maximum_weight: true, color: false, diameter: true, part_number: true, service_description: true, lateral_wall: true, rim_width_range: true, tred_depth: true, company: c})  
ProductCategory.create({name: "Llantas Camión", description: "Llantas Camión", length: true, width: true, maximum_pressure: true, maximum_weight: true, color: false, diameter: true, part_number: true, service_description: true, lateral_wall: true, rim_width_range: true, tred_depth: true, company: c})  
ProductCategory.create({name: "Rin Automóvil", description: "Rin Automóvil", length: true,  part_number: true, offset: true, pcd: true, holes: true, x_factor: true, company: c})  
ProductCategory.create({name: "Rin Camioneta", description: "Rin Camioneta", length: true,  part_number: true, offset: true, pcd: true, holes: true, x_factor: true, company: c})  

Distributor.create({company: c, name: 'AREA TUNING', address_1: 'CRA. 52 #38-11', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2324493', telephone_2: '2323035',email: 'areatuning@hotmail.com'})
Distributor.create({company: c, name: 'DAKAR WHEELS ', address_1: 'CRA. 65 # 42-13', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '5824957', email: 'dakarwheels@hotmail.com'})
Distributor.create({company: c, name: 'AUTO POWER', address_1: 'CRA, 100 # 104 A -33', city: 'Apartado', state: 'Antioquia', country: 'Colombia', telephone_1: '3147895724', telephone_2: '3155631957',email: 'jhonlopez43@hotmail.com'})
Distributor.create({company: c, name: 'DISTRIBUIDORA SERVILLANTAS URABA', address_1: 'CRA. 100 #110-16', city: 'Apartado', state: 'Antioquia', country: 'Colombia', telephone_1: '8288752', email: 'eugeniap@edatel.co'})
Distributor.create({company: c, name: 'JIMENEZ QUINTERO LUIS ALBERTO', address_1: 'CALLE 44 #59-38', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2317334'})
Distributor.create({company: c, name: 'JIMENEZ QUINTERO HECTOR ALONSO', address_1: 'CALLE 44 #57-A-06', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '5124768'})
Distributor.create({company: c, name: 'LA CASA DEL RIN', address_1: 'CALLE 44 #58-60', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '5142879', email: 'lacasadelrin2009@hotmail.com'})
Distributor.create({company: c, name: 'TORRES ALZATE LEONEL', address_1: 'CALLE 44 #59-86', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '5122084'})
Distributor.create({company: c, name: 'TODO RINES', address_1: 'CALLE 44 # 57-A-16', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '5124771', telephone_2: '3146848413',email: 'wveimarmuoz2009@hotmail.com'})
Distributor.create({company: c, name: 'LLANTECA VIRTUAL', address_1: 'CRA. 43 A # 25 A-21', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2627278', email: 'medellin@llanteca.com'})
Distributor.create({company: c, name: 'DISTRIBUIDORA V.C RIN SPEED', address_1: 'CALLE 33 # 65 C-118', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2653862', telephone_2: '3173837045',email: 'vcrinspeed@hotmail.com,distririnspeed@hotmail.com'})
Distributor.create({company: c, name: 'ORION LUJOS Y SONIDO S.A.', address_1: 'CRA. 52 #38-39', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2324152', email: 'almacenorion@gmail.com'})
Distributor.create({company: c, name: 'COMERCIAL LUCAR S.A.', address_1: 'CRA. 52 #38-27', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2324194', email: 'administradorlucar@une.net.co'})
Distributor.create({company: c, name: 'ECOLLANTAS LTDA', address_1: 'CRA. 52 # 38-70', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2324992', email: 'ecollantas1@une.net.co'})
Distributor.create({company: c, name: 'MEDIVIR S.A.S.', address_1: 'CRA. 50 # 39-32', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '4441024', email: 'medivir@hotmail.com'})
Distributor.create({company: c, name: 'LLANTECA DEL SUR Y CIA. LTDA', address_1: 'CRA. 43-A #25-A-21', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2627278', email: 'medellin@llanteca.com'})
Distributor.create({company: c, name: 'AUTO OLARTE S.A.', address_1: 'CRA. 50 #32-16', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2619600', email: 'jolarte@autolarte.com.co'})
Distributor.create({company: c, name: 'ANDAR S.A.', address_1: 'CALLE 29 #44-136', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '4440800'})
Distributor.create({company: c, name: 'AYURA MOTOR S.A.', address_1: 'CRA. 48 #26 SUR-27', city: 'Envigado', state: 'Antioquia', country: 'Colombia', telephone_1: '3321100'})
Distributor.create({company: c, name: 'LLANTAR S.A.S.', address_1: 'CENTRO CIAL. AUTOMOTRIZ L-15', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2620011', telephone_2: '2325508',email: 'llantarem@yahoo.es'})
Distributor.create({company: c, name: 'AUTOSHOP LLANTAS Y RINES S.A.S', address_1: 'CRA. 43A #19-A-87 L.7/8/9', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2623348', telephone_2: '2623323',email: 'rodolfosoto@hotmail.com'})
Distributor.create({company: c, name: 'ORION LUJOS Y SONIDO S.A.', address_1: 'CRA. 52 # 38-39', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2324152', email: 'almacenorion@gmail.com'})
Distributor.create({company: c, name: 'INTERLLANTAS', address_1: 'CALLE 44 # 64-37', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2306811', telephone_2: '2602531',email: 'interllantas@hotmail.com'})
Distributor.create({company: c, name: 'LLANTAS ONLINE S.A.S.', address_1: 'CALLE 44 # 64-37', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2306811', email: 'ivanvelasquez@llantasonline.com'})
Distributor.create({company: c, name: 'SUPERLLANTAS', address_1: 'CRA. 63D #42B-04', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '2352269'})
Distributor.create({company: c, name: 'MOGOYA TIRES', address_1: 'CALLE 44 # 58-70', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '5124787'})
Distributor.create({company: c, name: 'QUINTERO LOPEZ LUBIN ALFONSO', address_1: 'CALLE 44 # 58-70', city: 'Medellin', state: 'Antioquia', country: 'Colombia', telephone_1: '5124787', telephone_2: '3113081993'})
Distributor.create({company: c, name: 'SERVILLANTAS EL DORADO LTDA', address_1: 'CRA. 41 # 40 SUR 15', city: 'Envigado', state: 'Antioquia', country: 'Colombia', telephone_1: '3327133', telephone_2: '3327134',email: 'gerencia@servillantaseldorado.com.co'})
Distributor.create({company: c, name: 'AUTO RAPIDO', address_1: 'CRA 43 # 66-56', city: 'Barranquilla', state: 'Atlantico', country: 'Colombia', telephone_1: '3510229', email: 'auto-rapido@hotmail.com'})
Distributor.create({company: c, name: 'AUTO MUNDO SUPERLLANTAS S.A.S.', address_1: 'CALLE 74 # 45-07', city: 'Barranquilla', state: 'Atlantico', country: 'Colombia', telephone_1: '3686114', email: 'automundosuperllantas@gmail.com'})
Distributor.create({company: c, name: ' RINES  Y LLANTAS JUANDI', address_1: 'CRA. 43 # 64-38', city: 'Barranquilla', state: 'Atlantico', country: 'Colombia', telephone_1: '3406065', email: 'yanetdiaz22@hotmail.com'})
Distributor.create({company: c, name: 'LLANTAS VIVERO', address_1: 'CRA. 72 # 76-146', city: 'Barranquilla', state: 'Atlantico', country: 'Colombia', telephone_1: '3686436', email: 'llantasvivero@hotmail.com'})
Distributor.create({company: c, name: 'LA CASA DE RINES LUJOS Y ACCESORIOS LTDA', address_1: 'CRA. 43 # 65-B-11 L-1 Y 2', city: 'Barranquilla', state: 'Atlantico', country: 'Colombia', telephone_1: '3515896', email: 'casarinesltda@hotmail.com'})
Distributor.create({company: c, name: 'RINES Y LLANTAS OSCAR', address_1: 'CRA. 43 # 67-02 L-1', city: 'Barranquilla', state: 'Atlantico', country: 'Colombia', telephone_1: '3584755', email: 'rinesoscar@hotmail.com'})
Distributor.create({company: c, name: 'ALM. SU AUTO F.E.', address_1: 'BR.ESCAL VILLA AV.P.HER 52-90', city: 'Cartagena', state: 'Bolivar', country: 'Colombia', telephone_1: '6697052', email: 'elimart_220408@hotmail.com'})
Distributor.create({company: c, name: 'AUTOLUJOS DEL CARIBE', address_1: 'AV.P.DE HEREDIA CL.31 #51-92', city: 'Cartagena', state: 'Bolivar', country: 'Colombia', telephone_1: '6697096'})
Distributor.create({company: c, name: 'EXPOLUJOS ', address_1: 'CALLE 32  # 21-232', city: 'Cartagena', state: 'Bolivar', country: 'Colombia', telephone_1: '6565868', telephone_2: '3157430537',email: 'edwingg6@hotmail.com'})
Distributor.create({company: c, name: 'TODO EN LLANTAS  MARTINEZ', address_1: 'PIE DE LA POPA CLE.32 # 21-113', city: 'Cartagena', state: 'Bolivar', country: 'Colombia', telephone_1: '6660289', telephone_2: '6666998',email: 'janeth-diaz@hotmail.com'})
Distributor.create({company: c, name: 'LA CASA DEL RIN Y LA LLANTA LTDA', address_1: 'AV.CRISANTO LUQUE # 40-48', city: 'Cartagena', state: 'Bolivar', country: 'Colombia', telephone_1: '6623461', telephone_2: '3114119989',email: 'lacasadelrinyllanta@telecom.com'})
Distributor.create({company: c, name: 'SERVILLANTAS EL LAGO.', address_1: 'AVE. DEL LAGO # 17-214', city: 'Cartagena', state: 'Bolivar', country: 'Colombia', telephone_1: '6661212', email: 'servillantasellago@hotmail.com'})
Distributor.create({company: c, name: 'EXPOLLANTAS Y LUJOS', address_1: 'AV.P.HERED CL.31A #49E-4VIENTO', city: 'Cartagena', state: 'Bolivar', country: 'Colombia', telephone_1: '6699281', telephone_2: '6697374',email: 'expollantasylujos@hotmail.com'})
Distributor.create({company: c, name: 'CELY LLANTAS', address_1: 'CRA. 20 #11A BIS-26', city: 'Sogamoso', state: 'Boyaca', country: 'Colombia', telephone_1: '7720897', email: 'celyllantas@hotmail.com'})
Distributor.create({company: c, name: 'MONTA¥EZ CARO AURA MARY', address_1: 'AVE.SAN MARTIN # 12-38', city: 'Sogamoso', state: 'Boyaca', country: 'Colombia', telephone_1: '7704233', telephone_2: '3012375160'})
Distributor.create({company: c, name: 'MAXILLANTAS SOGAMOSO', address_1: 'CALLE 11 B # 17-43', city: 'Sogamoso', state: 'Boyaca', country: 'Colombia', telephone_1: '3103378400', telephone_2: '3123508688'})
Distributor.create({company: c, name: 'LLANTAS BOYACA', address_1: 'AVE.ORIENTAL 2A # 3-73', city: 'Tunja', state: 'Boyaca', country: 'Colombia', telephone_1: '7404894', telephone_2: '7449583',email: 'llantasboyaca@hotmail.com'})
Distributor.create({company: c, name: 'SERVIAMERICAS', address_1: 'CALLE 20 # 22-47', city: 'Duitama', state: 'Boyaca', country: 'Colombia', telephone_1: '7621397', telephone_2: '7629543'})
Distributor.create({company: c, name: 'LUBERLLANTAS', address_1: 'CALLE 15 19 32', city: 'Duitama', state: 'Boyaca', country: 'Colombia', telephone_1: '7630696', email: 'luberllantas1@telecom.com.co'})
Distributor.create({company: c, name: 'LANTAS SAN DIEGO', address_1: 'CALLE 12A #30-52 AV.CIRCUNV.', city: 'Duitama', state: 'Boyaca', country: 'Colombia', telephone_1: '7619448'})
Distributor.create({company: c, name: 'CENTRO DE REENCAUCHE', address_1: 'CRA. 41 # 10-31', city: 'Duitama', state: 'Boyaca', country: 'Colombia', telephone_1: '7614266'})
Distributor.create({company: c, name: 'SERVILLANTAS LA ESTACION', address_1: 'CRA. 18 # 23-30', city: 'Duitama', state: 'Boyaca', country: 'Colombia', telephone_1: '7626796', telephone_2: '3123512644'})
Distributor.create({company: c, name: 'CENTRO SERVICIOS LIBERTADORES', address_1: 'CALLE 11 # 29-85', city: 'Sogamoso', state: 'Boyaca', country: 'Colombia', telephone_1: '7715999', telephone_2: '3108823154',email: 'libertadoresfstp@gmail.com'})
Distributor.create({company: c, name: 'MUNDILLANTAS', address_1: 'CRA. 20 # 10-36', city: 'Sogamoso', state: 'Boyaca', country: 'Colombia', telephone_1: '7700782', telephone_2: '7827812'})
Distributor.create({company: c, name: 'ALMACEN BISELUJOS', address_1: 'CALLE 21 #12-57', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8835419', telephone_2: '8844702'})
Distributor.create({company: c, name: 'SUPER CAR AUDIO', address_1: 'CALLE 48 A # 27-31', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8855606', telephone_2: '3113679783',email: 'supercaraudio@telmex.net.co'})
Distributor.create({company: c, name: 'MUSIRUEDAS', address_1: 'CRA. 19 #29-40', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8841342', email: 'musi-ruedas@hotmail.com'})
Distributor.create({company: c, name: 'CINTAS Y LUJOS', address_1: 'CRA. 25 #46-42', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8835249', telephone_2: '3148146441',email: 'cintasylujosmanizales@hotmail.com'})
Distributor.create({company: c, name: 'GONZA S.A.', address_1: 'AVE. 18 #28-29', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8803687', telephone_2: '8842160',email: 'contacto@gonza.co'})
Distributor.create({company: c, name: 'CASA LOPEZ', address_1: 'CRA. 23 #39-39', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8845960', telephone_2: '8840225',email: 'llantas@casalopez.com.co'})
Distributor.create({company: c, name: 'RADIOS Y RINES S.A.', address_1: 'CRA. 24 #47-45', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8863800', telephone_2: '8813050',email: 'lore2102@hotmail.com'})
Distributor.create({company: c, name: 'SUPERLLANTAS INVERSIONES S.A.S.', address_1: 'CALLE 21 # 14-40', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8801934', email: 'jmt03@hotmail.com'})
Distributor.create({company: c, name: 'COMERCIALIZADORA DE LLANTAS', address_1: 'AV. CENTENARIO # 23-01', city: 'Manizales', state: 'Caldas', country: 'Colombia', telephone_1: '8820817', email: 'comercializadoradellantas1@hotmail.com'})
Distributor.create({company: c, name: 'DISTRILLANTAS R.E. S.A.S.', address_1: 'CLE 17 CRA. 11 ESQ.BRR CENTRO', city: 'Florencia', state: 'Caqueta', country: 'Colombia', telephone_1: '4352977', telephone_2: '3143940466',email: 'distrillantas@gmail.com'})
Distributor.create({company: c, name: 'MAXILLANTAS', address_1: 'CRA. 10 # 16-62', city: 'Florencia', state: 'Caqueta', country: 'Colombia', telephone_1: '4340571', email: 'maxillantas.ana@gmail.com'})
Distributor.create({company: c, name: 'LAVAAUTOS CHUCURI', address_1: 'CALLE 27 # 19-06', city: 'Yopal', state: 'Casanare', country: 'Colombia', telephone_1: '6342052', email: 'lavautoschucuri@hotmail.com'})
Distributor.create({company: c, name: 'MERCALLANTAS', address_1: 'CALLE 24 # 16-A-11', city: 'Yopal', state: 'Casanare', country: 'Colombia', telephone_1: '6322744', telephone_2: '3108690374',email: 'y-li@hotmail.com'})
Distributor.create({company: c, name: 'NOVA GONZALEZ CARLOS', address_1: 'CALLE 24 # 11-48', city: 'Yopal', state: 'Casanare', country: 'Colombia', telephone_1: '6320942'})
Distributor.create({company: c, name: 'DISTRILLANTAS MILENIUM LIMITADA', address_1: 'CALLE 24 #13-02', city: 'Yopal', state: 'Casanare', country: 'Colombia', telephone_1: '6359132', email: 'llantamilenium@hotmail.com'})
Distributor.create({company: c, name: 'PARRA PRIETO JOSE ORLANDO', address_1: 'CALLE 18 # 23-24', city: 'Yopal', state: 'Casanare', country: 'Colombia', telephone_1: '6343694'})
Distributor.create({company: c, name: 'SERVITECA AUTO CAUCA', address_1: 'DIAGN 17 # 2N-19 FRENTE INEM', city: 'Popayan', state: 'Cauca', country: 'Colombia', telephone_1: '8231816', email: 'serviautocauca@hotmail.com'})
Distributor.create({company: c, name: 'COMER.SERVIOCCIDENTE', address_1: 'CALLE 5 # 21-06', city: 'Popayan', state: 'Cauca', country: 'Colombia', telephone_1: '8229752', telephone_2: '3113898090'})
Distributor.create({company: c, name: 'CENTROCARROS S.A.', address_1: 'CRA. 9 # 54-N-105', city: 'Popayan', state: 'Cauca', country: 'Colombia', telephone_1: '8326035', telephone_2: '8329562',email: 'centrocarros@emtel.net.co'})
Distributor.create({company: c, name: 'MULTILLANTAS', address_1: 'CALLE 5 # 36-90', city: 'Popayan', state: 'Cauca', country: 'Colombia', telephone_1: '8306161', email: 'noraldihoyos@hotmail.com'})
Distributor.create({company: c, name: 'SERVILLANTAS PALERMO', address_1: 'CRA. 7 # 20-08', city: 'Valledupar', state: 'Cesar', country: 'Colombia', telephone_1: '5707123'})
Distributor.create({company: c, name: 'FORROS Y LLANTAS LA 19', address_1: 'CRA. 19 # 14-29 BR.SAN VICENTE', city: 'Valledupar', state: 'Cesar', country: 'Colombia', telephone_1: '5711359', telephone_2: '3106859183',email: 'forrosyllanta19@hotmail.com'})
Distributor.create({company: c, name: 'CREDILLANTAS', address_1: 'DIAGN. 21 #18-D-25', city: 'Valledupar', state: 'Cesar', country: 'Colombia', telephone_1: '5802075', email: 'credillantas-@hotmail.com'})
Distributor.create({company: c, name: 'LLANTAS Y SERVICIOS PALERMO', address_1: 'CRA. 7 #20-08', city: 'Valledupar', state: 'Cesar', country: 'Colombia', telephone_1: '5707123', telephone_2: '3003001065',email: 'jesusustariz@hotmail.com'})
Distributor.create({company: c, name: 'AUTO SERVICIOS INTEGRALES LTDA', address_1: 'CRA. 18 D #21-44 BRR SIMON BOL', city: 'Valledupar', state: 'Cesar', country: 'Colombia', telephone_1: '5708080', telephone_2: '3176436673',email: 'autoserviciosintegrales@hotmail.com'})
Distributor.create({company: c, name: 'AUTO LLANTAS', address_1: 'CRA. 2 #40-00', city: 'Monteria', state: 'Cordoba', country: 'Colombia', telephone_1: '7822931', email: 'ivanagamez@hotmail.com'})
Distributor.create({company: c, name: 'AUTOTECH TUNNING', address_1: 'CRA. 4 # 44-43', city: 'Monteria', state: 'Cordoba', country: 'Colombia', telephone_1: '7852678', telephone_2: '3008167572'})
Distributor.create({company: c, name: 'EL PARAISO DE LAS LLANTAS', address_1: 'CRA. 25 # 4A-07', city: 'Lorica', state: 'Cordoba', country: 'Colombia', telephone_1: '7735348', email: 'blasantonioms@hotmail.com'})
Distributor.create({company: c, name: 'ALMACEN SURTILLANTAS', address_1: 'CRA. 2 # 41-71', city: 'Monteria', state: 'Cordoba', country: 'Colombia', telephone_1: '7824118', email: 'jonemo41@hotmail.com'})
Distributor.create({company: c, name: 'DORIAUTOS', address_1: 'CRA. 2  NO. 40-09', city: 'Monteria', state: 'Cordoba', country: 'Colombia', telephone_1: '7824654'})
Distributor.create({company: c, name: 'REYES PALMERA JAIME', address_1: 'CALLE 41 NO. 8-37', city: 'Monteria', state: 'Cordoba', country: 'Colombia', telephone_1: '7822608', telephone_2: '3145961298',email: 'jaimereyesp@hotmail.com'})
Distributor.create({company: c, name: 'ALMACEN SUPER Y CIA LTDA', address_1: 'CRA. 2 #43-54', city: 'Monteria', state: 'Cordoba', country: 'Colombia', telephone_1: '7823549', telephone_2: '7820937',email: 'luismhoyos@msn.com'})
Distributor.create({company: c, name: 'JIMENEZ MOLANO JOHNNIE HERNANDO', address_1: 'CRA. 9 # 3-62', city: 'Zipaquira', state: 'Cundinamarca', country: 'Colombia', telephone_1: '8522382'})
Distributor.create({company: c, name: 'MULTILLANTAS LA SABANA', address_1: 'CALLE 195 #40-93', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '6702773', telephone_2: '6701311',email: 'multillantaslasabana@yahoo.com'})
Distributor.create({company: c, name: 'GAYON VASQUEZ FREDY ANTONIO', address_1: 'CALLE 8 # 23-36', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2016368'})
Distributor.create({company: c, name: 'LLANTAS CAMEL', address_1: 'CRA. 23 #7-39', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '3710504'})
Distributor.create({company: c, name: 'ABC DE LOS RINES', address_1: 'CRA. 17 CALLE 68 ESQ.', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2102628', telephone_2: '2104087'})
Distributor.create({company: c, name: 'SCN LLANTAS Y RINES', address_1: 'CRA. 38 # 6-15', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2474646', telephone_2: '3512802'})
Distributor.create({company: c, name: 'DIEFEL CAR', address_1: 'CRA. 36 #8A-21', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2471049', email: 'diefelcar@hotmail.com'})
Distributor.create({company: c, name: 'SUPER LUJOS DEL NORTE', address_1: 'CRA.41 #195-08 SAN ANDRES.NORT', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '6787665', telephone_2: '6749157'})
Distributor.create({company: c, name: 'LLANTAS Y RINES CO', address_1: 'CALLE 8 #22-26', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2014569', email: 'magnoly_8@hotmail.com, hecfranrico@hotmail.com'})
Distributor.create({company: c, name: 'COMERCIALIZADORA DE LLANTAS', address_1: 'DIAGN. 7 # 39-27', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '4050931', telephone_2: '2771058',email: 'llantaspr@hotmail.com'})
Distributor.create({company: c, name: 'SURTILLANTAS CRIS', address_1: 'CALLE 8 #22-42', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '3604328'})
Distributor.create({company: c, name: 'MUNDIRINES', address_1: 'CALLE 8 #23-34', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2011937', telephone_2: '3103495655',email: 'mundirines@hotmail.com'})
Distributor.create({company: c, name: 'AUTO LUJOS DINASTIA', address_1: 'CRA 38 # 6-44 LOCAL 111/112', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '3607847', telephone_2: '3607859',email: 'san_sanmor@hotmail.com'})
Distributor.create({company: c, name: 'CARDENAS DUARTE LUZ MARY', address_1: 'CALLE 8 #22-16', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2475507'})
Distributor.create({company: c, name: 'FULL SPEED', address_1: 'CALLE 8 #22-51', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '5616806', telephone_2: '2470418',email: 'normape@hotmail.com'})
Distributor.create({company: c, name: 'LLANTAS Y RINES EL BOYACO ', address_1: 'DIAGN. 7 # 38-40 L-103', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '4052883', email: 'llantasyrineselboyaco@hotmail.com'})
Distributor.create({company: c, name: 'NI¥O PAEZ LUZ ANGELA', address_1: 'CRA. 23 #7-90', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '3704276', telephone_2: '3118224788'})
Distributor.create({company: c, name: 'RINES Y LLANTAS BETO', address_1: 'CRA. 23 #8-31', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2475111'})
Distributor.create({company: c, name: 'SERVILLANTAS DEL PRADO', address_1: 'CALLE 134 #47-22', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2587152', telephone_2: '2169815'})
Distributor.create({company: c, name: 'CASTA¥O RAMIREZ OMAR ENRIQUE', address_1: 'CRA. 23 #8-14', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '4077445', email: 'comercializadoraomencar@yahoo.com'})
Distributor.create({company: c, name: 'ARIZA CANO MARCO FIDEL', address_1: 'CALLE 8 NO. 22-45', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2478244'})
Distributor.create({company: c, name: 'LLANTAS Y RINES AUGUSTO', address_1: 'CRA. 38 #6-55', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '3607873', telephone_2: '2779272'})
Distributor.create({company: c, name: 'INFANTE SANTANA RODRIGO ERNESTO', address_1: 'CALLE 72 # 27B-08 LC 102', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2506667'})
Distributor.create({company: c, name: 'SOLO RINES Y LLANTAS', address_1: 'CALLE 8 #23-35', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2379267', email: 'solorinesyllantas@hotmail.com'})
Distributor.create({company: c, name: 'SERVILLANTAS QUIROGA', address_1: 'CALLE 27 SUR #24A-05', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2095499'})
Distributor.create({company: c, name: 'COMERCIALIZADORA .DIMS', address_1: 'CRA. 38 # 6-28 L-102', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '4057442'})
Distributor.create({company: c, name: 'ARIZA CANO VILLA LEONARDO', address_1: 'CRA. 8 #23-14', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2474298', telephone_2: '4091578'})
Distributor.create({company: c, name: 'MAXI RINES R.C.', address_1: 'CALLE 8 #22-07', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '5669691', telephone_2: '3706483',email: 'quintero33raul@yahoo.es'})
Distributor.create({company: c, name: 'TOTO TIRE', address_1: 'CRA. 23 #7-95', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '3711483', telephone_2: '2779527'})
Distributor.create({company: c, name: 'ALINEACIONES JAIME B LTDA.', address_1: 'CALLE  79 # 27-A-20', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '3118573', telephone_2: '5424524',email: 'alineacionesjaimeb@hotmail.com'})
Distributor.create({company: c, name: 'RAMOS ALDANA ABRAHAM ANDRES', address_1: 'CRA. 39 # 7-05', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '4052570', telephone_2: '3002175296',email: 'andresfincomercio@yahoo.com'})
Distributor.create({company: c, name: 'RINCON RIOS SCS', address_1: 'DIAGN. 7 #38-10', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2477451', telephone_2: '3711836'})
Distributor.create({company: c, name: 'AUTO RINES Y LLANTAS LTDA.', address_1: 'CRA. 38 #6-25', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '3607557', email: 'autorinesyllantas@hotmail.com'})
Distributor.create({company: c, name: 'IMPORTADORA NACIONAL DE LLANTAS S.A', address_1: 'CRA. 106 #15-25 MZ 12 L-72/73', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '4046989', telephone_2: '3102997291'})
Distributor.create({company: c, name: 'DISTRIBUIDORA NISSAN S.A.', address_1: 'CALLE 13 # 50-69', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '5943203', telephone_2: '2629265'})
Distributor.create({company: c, name: 'LLANTAS BOGOTA LTDA', address_1: 'CRA. 16 # 61-A-48', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2111947', telephone_2: '5473177',email: 'llantasbogota@gmail.com'})
Distributor.create({company: c, name: 'LA ESQUINA', address_1: 'CRA.13 NO.74-00', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2102488', telephone_2: '3217512'})
Distributor.create({company: c, name: 'ALMACEN LA LLANTA LTDA', address_1: 'CRA. 23 #7-82/84', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2012715', email: 'alallanta@gmail.com'})
Distributor.create({company: c, name: 'LLANTAS Y SERVICIOS LOS HEROES S.A.', address_1: 'CRA. 19 #76-79', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '2175156', telephone_2: '2557721',email: 'llantasheroes@etb.net.co'})
Distributor.create({company: c, name: 'INVERSIONES LEARDI S.A.', address_1: 'CRA. 52 # 29-29 SUR', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '4071209', telephone_2: '4087080',email: 'ardillantas@hotmail.com'})
Distributor.create({company: c, name: 'RAMOS ALDANA JESSICA', address_1: 'CALLE 9 36-44 LOCAL 5', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '5602288', telephone_2: '3111597790'})
Distributor.create({company: c, name: 'RINES RECSAN S.A.S.', address_1: 'CALLE 7 # 37A-73 LC-116', city: 'Bogota', state: 'Cundinamarca', country: 'Colombia', telephone_1: '5604382', email: 'rafacob521@hotmail.com'})
Distributor.create({company: c, name: 'LLANTAS EL MONO', address_1: 'CALLE 16 # 11-25', city: 'Maicao', state: 'Guajira', country: 'Colombia', telephone_1: '7254420', telephone_2: '3135006690',email: 'nabil_yebara@hotmail.com'})
Distributor.create({company: c, name: 'ALMACEN  RODIAUTOS', address_1: 'CRA. 3 # 1-21 SUR', city: 'Pitalito', state: 'Huila', country: 'Colombia', telephone_1: '8361234', telephone_2: '3142195543'})
Distributor.create({company: c, name: 'CENTRO LLANTAS', address_1: 'CRA. 3 # 1-41', city: 'Pitalito', state: 'Huila', country: 'Colombia', telephone_1: '8369401'})
Distributor.create({company: c, name: 'BRAVO TOVAR SANDI', address_1: 'CRA. 1 # 17-A-73 SUR', city: 'Pitalito', state: 'Huila', country: 'Colombia', telephone_1: '3143577799'})
Distributor.create({company: c, name: 'JAGUTI', address_1: 'CALLE 16 #10-25', city: 'Neiva', state: 'Huila', country: 'Colombia', telephone_1: '8752545', email: 'jaguti3@hotmail.com'})
Distributor.create({company: c, name: 'AMORTILUJOS', address_1: 'CRA. 5 #24-34', city: 'Santa marta', state: 'Magdalena', country: 'Colombia', telephone_1: '4210076'})
Distributor.create({company: c, name: 'REPAUTOS LTDA', address_1: 'CRA. 5 #26B-59', city: 'Santa marta', state: 'Magdalena', country: 'Colombia', telephone_1: '4312405', telephone_2: '4310063'})
Distributor.create({company: c, name: 'GIL A. GARCIA Y CIA. LTDA', address_1: 'CALLE 23 #4-69', city: 'Santa marta', state: 'Magdalena', country: 'Colombia', telephone_1: '4214734', telephone_2: '4210167'})
Distributor.create({company: c, name: 'SERVICENTRO RODADERO', address_1: 'CLE 19 #3-71 L-A RODADERO SUR', city: 'Santa marta', state: 'Magdalena', country: 'Colombia', telephone_1: '3015757776', email: 'servicentro-rodadero@hotmail.com'})
Distributor.create({company: c, name: 'ORIENTAL DE LLANTAS', address_1: 'CALLE 31 # 23-41 B. PORVENIR', city: 'Villavicencio', state: 'Meta', country: 'Colombia', telephone_1: '6715241', email: 'orientaldellantas@hotmail.com'})
Distributor.create({company: c, name: 'MEGALLANTAS DEL LLANO', address_1: 'CALLE 15 #7-30 AV.MARACOS', city: 'Villavicencio', state: 'Meta', country: 'Colombia', telephone_1: '6720761', email: 'megallantasayadelllano@hotmail.com'})
Distributor.create({company: c, name: 'AUTO RALLY W', address_1: 'CRA. 27 #32-02 L-114', city: 'Villavicencio', state: 'Meta', country: 'Colombia', telephone_1: '6731957', telephone_2: '3102420281',email: 'noralbarubio@gmail.com'})
Distributor.create({company: c, name: 'LLANTOTAS DEL META', address_1: 'CRA. 27 # 33-05/07 B.PORVENIR', city: 'Villavicencio', state: 'Meta', country: 'Colombia', telephone_1: '3123028829', email: 'llantotasdelmeta@hotmail.com'})
Distributor.create({company: c, name: 'VANEGAS PARRA ALDEMAR', address_1: 'CRA. 23 # 10-53 DORADO ALTO', city: 'Acacias', state: 'Meta', country: 'Colombia', telephone_1: '6469793'})
Distributor.create({company: c, name: 'MAXILLANTAS LTDA. V/CIO.', address_1: 'CRA. 33 # 20-71 LA FLORIDA', city: 'Villavicencio', state: 'Meta', country: 'Colombia', telephone_1: '6633871', telephone_2: '6705008',email: 'maxillantasltda@yahoo.es'})
Distributor.create({company: c, name: 'EDUARDS LLANTAS', address_1: 'CALLE 15 # 9 B-05 AV.MARACOS', city: 'Villavicencio', state: 'Meta', country: 'Colombia', telephone_1: '6608846', email: 'eduardsllantas7@hotmail.com'})
Distributor.create({company: c, name: 'LLANTAS SERVINOVA', address_1: 'CRA. 23 #5-70 BRR ALBORADA', city: 'Villavicencio', state: 'Meta', country: 'Colombia', telephone_1: '3102041513'})
Distributor.create({company: c, name: 'CARRILLO ANTONIO MARIA', address_1: 'AVE. 7 # 0-49', city: 'Cucuta', state: 'Norta de Santander', country: 'Colombia', telephone_1: '5780564', telephone_2: '5790117',email: 'antonio.carrillo@une.net.co'})
Distributor.create({company: c, name: 'CAUCHOS CUCUTA E', address_1: 'AV.GRAN COLOMBIA # 3A-23', city: 'Cucuta', state: 'Norta de Santander', country: 'Colombia', telephone_1: '5780317', email: 'cauchoscucuta@hotmail.com, antocaju@hotmail.com'})
Distributor.create({company: c, name: 'SERVITECA ROSETAL', address_1: 'DIAGONAL SANTANDER # 4E-95', city: 'Cucuta', state: 'Norta de Santander', country: 'Colombia', telephone_1: '5716905', telephone_2: '5718740',email: 'careli_gomez@hotmail.com'})
Distributor.create({company: c, name: 'MAXLLANTAS CUCUTA S.A.', address_1: 'AVE. 7 #2-87 BRR EL CALLEJON', city: 'Cucuta', state: 'Norta de Santander', country: 'Colombia', telephone_1: '5833508', email: 'maxllantascucuta@yahoo.es'})
Distributor.create({company: c, name: 'MULTICAUCHOS', address_1: 'AV. 3 # 0-83 BRRIO LLERAS CAMA', city: 'Cucuta', state: 'Norta de Santander', country: 'Colombia', telephone_1: '5771410', email: 'mcym_72@hotmail.com'})
Distributor.create({company: c, name: 'AUTORACING', address_1: 'CALLE 1 # 7 E-137 QUINTA ORIEN', city: 'Cucuta', state: 'Norta de Santander', country: 'Colombia', telephone_1: '5753775', email: 'johan_izaquita_m@yahoo.com'})
Distributor.create({company: c, name: 'MULTISERVICIO CAR EXPRESS', address_1: 'AVE. 3 # 14-40 SAN LUIS', city: 'Cucuta', state: 'Norta de Santander', country: 'Colombia', telephone_1: '3114403073', email: 'linaortizquintero@hotmail.com'})
Distributor.create({company: c, name: 'AUTOLIBERTADOR', address_1: 'AV.LIBERTADORES 9B-N-17 L-2', city: 'Cucuta', state: 'Norta de Santander', country: 'Colombia', telephone_1: '5744043', telephone_2: '3208502249',email: 'samuelmonsalve@yahoo.com'})
Distributor.create({company: c, name: 'STREET WHEELS', address_1: 'AVE. CHAMPAGNAT # 14-43', city: 'Pasto', state: 'Nariño', country: 'Colombia', telephone_1: '7217960'})
Distributor.create({company: c, name: 'LLANTAS SAN FERNANDO', address_1: 'CRA. 19 NO. 11-55', city: 'Armenia', state: 'Quindio', country: 'Colombia', telephone_1: '7465290', email: 'llantas_sanfernando@hotmail.com'})
Distributor.create({company: c, name: 'MANRIQUE ALVAREZ FERNANDO', address_1: 'TERMINAL TRANSP. ARMENIA  L-11', city: 'Armenia', state: 'Quindio', country: 'Colombia', telephone_1: '7475588'})
Distributor.create({company: c, name: 'LOS PITS AUTOSONIDO', address_1: 'CRA. 19 #9-22', city: 'Armenia', state: 'Quindio', country: 'Colombia', telephone_1: '7456904'})
Distributor.create({company: c, name: 'ARIAS TABARES S.A.S', address_1: 'CALLE 12 #19-45 L-25', city: 'Armenia', state: 'Quindio', country: 'Colombia', telephone_1: '7469898', telephone_2: '7469835'})
Distributor.create({company: c, name: 'DILLANCOL S.A.', address_1: 'CRA. 19 # 3-30', city: 'Armenia', state: 'Quindio', country: 'Colombia', telephone_1: '7463020', email: 'dillancolarmenia@telecom.com.co'})
Distributor.create({company: c, name: 'TECNODIESEL Y AUTOPARTES S.A.S.', address_1: 'CALLE 35 # 20-68 INT.T.TRANSP', city: 'Armenia', state: 'Quindio', country: 'Colombia', telephone_1: '7475566'})
Distributor.create({company: c, name: 'AUDIO RUEDAS', address_1: 'CRA. 19 # 9-39', city: 'Armenia', state: 'Quindio', country: 'Colombia', telephone_1: '7452525', email: 'audioruedas@une.net.co'})
Distributor.create({company: c, name: 'GIRALDO GALLO DIEGO MAURICIO', address_1: 'CRA. 9 #34-52', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3293189', email: 'yako817@hotmail.com'})
Distributor.create({company: c, name: 'AUTO LLANTAS Y RINES', address_1: 'CRA. 12 #28-B-10', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3296120', telephone_2: '3296441',email: 'autollantasyrines@hotmail.com'})
Distributor.create({company: c, name: 'VULCANIZADORA TOLIMA', address_1: 'CRA. 18 # 22-B-07', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3216854', telephone_2: '3108243555',email: 'llantastolimapereira@hotmail.com'})
Distributor.create({company: c, name: 'KALILLANTA', address_1: 'CRA. 11 #34-18', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3265648'})
Distributor.create({company: c, name: 'AUTOLANDIA', address_1: 'CRA. 11 #34-41', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3364029'})
Distributor.create({company: c, name: 'NACHO LUJOS', address_1: 'CALLE 35 # 9-01', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3364029'})
Distributor.create({company: c, name: 'MARULANDA PANESSO PAOLA ANDREA', address_1: 'CRA. 9 #34-52', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3293189'})
Distributor.create({company: c, name: 'MARULANDA PANESSO NATALIA', address_1: 'CRA. 9 # 34-52', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3244554'})
Distributor.create({company: c, name: 'CAR STEREO BOUTIQUE', address_1: 'CRA. 9 #30-67', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3367000', email: 'carstereo@une.net.co'})
Distributor.create({company: c, name: 'LOPEZ ALVAREZ Y CIA S.C.A.', address_1: 'AVE. 30 DE AGOSTO #26-51', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3335656', telephone_2: '3252703',email: 'llantas@casalopez.com.co'})
Distributor.create({company: c, name: 'AUTO SONIDO', address_1: 'CRA. 11 CALLE 34 ESQUINA', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3369360'})
Distributor.create({company: c, name: 'FULL TRACCION', address_1: 'AVE. 30 DE AGOSTO # 27-09', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3263370', email: 'fulltraccionpereira@hotmail.com'})
Distributor.create({company: c, name: 'DISTRILLANTAS S.A.', address_1: 'AVE. 30 DE AGOSTO #28-40', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3361031', telephone_2: '3361708',email: 'distrillantaspereira@gmail.com'})
Distributor.create({company: c, name: 'ESTACION DE SERVICIOS DE PEREIRA', address_1: 'AVE. 30 DE AGOSTO # 26-72', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3336291', telephone_2: '3357410',email: 'ess.pereiraltda@etp.net.co'})
Distributor.create({company: c, name: 'R AUDIO Y SEG', address_1: 'CRA. 11 # 34-44', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3444652'})
Distributor.create({company: c, name: 'AMERICAN RINES Y LLANTAS', address_1: 'CRA. 12 # 29-03', city: 'Pereira', state: 'Risaralda', country: 'Colombia', telephone_1: '3263832'})
Distributor.create({company: c, name: 'TYPER CAR CENTER', address_1: 'CRA. 27 # 14-48', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '3164541341', telephone_2: '6358603',email: 'carvich@hotmail.com'})
Distributor.create({company: c, name: 'TUNE UP COMPANY', address_1: 'AVE. GONZALEZ VALENCIA # 50-24', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '3112088121', telephone_2: '3174296123',email: 'bytuneup@msn.com'})
Distributor.create({company: c, name: 'GRANDES LLANTAS', address_1: 'CRA. 25 # 28-22', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '6944343', email: 'grandesllantas@hotmail.com'})
Distributor.create({company: c, name: 'IMPORLLANTAS', address_1: 'CRA.20 # 18-25 B.SAN FRANCISCO', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '6320470', email: 'yolimaimporllantas@hotmail.com'})
Distributor.create({company: c, name: 'LLANTAS PALONEGRO', address_1: 'AVE.QUEBRADA SECA #20-71', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '6343725', telephone_2: '6422535'})
Distributor.create({company: c, name: 'SURTILLANTAS SANTANDER', address_1: 'CRA. 17 # 55-121', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '6741341'})
Distributor.create({company: c, name: 'EUROLLANTAS', address_1: 'CALLE 55 # 21-12 CONCORDIA', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '6576686', email: 'alvaradosamir@hotmail.com'})
Distributor.create({company: c, name: 'GARCILLANTAS S.A.', address_1: 'AVE. QUEBRADA SECA #13-07', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '6339702', email: 'garprincipal@telebucaramanga.net.co'})
Distributor.create({company: c, name: 'LUJOS Y ACCESORIOS  LA PLACA', address_1: 'CALLE 22 #18-02', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '6331719', email: 'laplaca22@hotmail.com'})
Distributor.create({company: c, name: 'SERVICENTRO .LA ESTRELLA', address_1: 'CRA. 15 W # 45-24', city: 'Bucaramanga', state: 'Santander', country: 'Colombia', telephone_1: '6707166'})
Distributor.create({company: c, name: 'RINES Y LLANTAS', address_1: 'CALLE 25 # 27-129 AV.LAS PE¥IT', city: 'Sincelejo', state: 'Sucre', country: 'Colombia', telephone_1: '3012475408'})
Distributor.create({company: c, name: 'AUTO LUJOS DEL CARIBE', address_1: 'AV.LAS PE¥ITAS CLE.25 #27-89', city: 'Sincelejo', state: 'Sucre', country: 'Colombia', telephone_1: '2804331', email: 'samuel0118@hotmail.com'})
Distributor.create({company: c, name: 'TUNING CAR', address_1: 'CALLE 32 # 28-151 AV. MARISCAL', city: 'Sincelejo', state: 'Sucre', country: 'Colombia', telephone_1: '3003472813'})
Distributor.create({company: c, name: 'L Y LL DEL NORTE S.A.', address_1: 'CALLE 25 #28-08 AV.LAS PE¥ITAS', city: 'Sincelejo', state: 'Sucre', country: 'Colombia', telephone_1: '2801183', telephone_2: '2802007',email: 'wildervilladiego@hotmail.co'})
Distributor.create({company: c, name: 'INTERLLANTAS', address_1: 'CALLE 25-A #28-73', city: 'Sincelejo', state: 'Sucre', country: 'Colombia', telephone_1: '2801095', email: 'saaddavid@gmail.com'})
Distributor.create({company: c, name: 'AUTORRINES', address_1: 'CRA. 6 # 31-A-49', city: 'Ibague', state: 'Tolima', country: 'Colombia', telephone_1: '2641507', email: 'autorines@gmail.com'})
Distributor.create({company: c, name: 'TECNICENTRO LLANTAS 5A. AVENIDA', address_1: 'CRA. 5 # 27-01', city: 'Ibague', state: 'Tolima', country: 'Colombia', telephone_1: '2645567'})
Distributor.create({company: c, name: 'JIMENEZ ARIAS WILSON', address_1: 'CRA. 2 # 27-20 SN PEDRO ALEJAN', city: 'Ibague', state: 'Tolima', country: 'Colombia', telephone_1: '2651098'})
Distributor.create({company: c, name: 'MULTISERVICIOS LA ESTACION', address_1: 'CALLE 6 #18-10', city: 'Buga', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '2373355'})
Distributor.create({company: c, name: 'TRUCKIN', address_1: 'CALLE 36 #42-C-04', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '3268123'})
Distributor.create({company: c, name: 'LLANTAS R.T.', address_1: 'CRA. 30 # 20-33', city: 'Tulua', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '2258243', telephone_2: '3116172349',email: 'llantasrt2011@hotmail.com'})
Distributor.create({company: c, name: 'SALVA LLANTAS JC', address_1: 'AVE. 3N #40-199', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '6646600', telephone_2: '6825251'})
Distributor.create({company: c, name: 'TECNICENTRO S.M', address_1: 'AVE. 6N #22-61', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '6617569'})
Distributor.create({company: c, name: 'VULCANIZADORA Y LLANT', address_1: 'AUTOP.SUR ORIENTAL #13 B -56', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '5578653', telephone_2: '5570884'})
Distributor.create({company: c, name: 'LLANTAS Y REENCAUCHE', address_1: 'CRA. 16 # 17-02 ESQ.', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '6820514'})
Distributor.create({company: c, name: 'LLANTAS DE OCCIDENTE', address_1: 'CALLE 10#12-45', city: 'Cartago', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '2128803'})
Distributor.create({company: c, name: 'SUPERSERVICIOS LM', address_1: 'CALLE 10 # 53-05', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '3959894'})
Distributor.create({company: c, name: 'SUPERLLANTAS GINEBRA', address_1: 'CRA. 7 # 24-26', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '8881285', telephone_2: '8881437',email: 'superllantasginebra@yahoo.es'})
Distributor.create({company: c, name: 'MONTALLANTAS RAMIREZ', address_1: 'CALLE 7 # 30 A-55', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '8850162'})
Distributor.create({company: c, name: 'LUBRILLANTAS EL SAMAN', address_1: 'CALLE 9 # 3-51', city: 'Roldanillo', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '2294646'})
Distributor.create({company: c, name: 'RINES DEL NORTE', address_1: 'AVE. 6N # 40-80', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '6649130', email: 'gerencia@rinesdelnorte.com'})
Distributor.create({company: c, name: 'AUTO CONSOLA', address_1: 'CALLE 8 #31-A-40', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '5571954', telephone_2: '5571958',email: 'elprecioso62@hotmail.com'})
Distributor.create({company: c, name: 'LLANTECA DEL SUR', address_1: 'CLE. 8 No.30-11 ESQ.', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '5565559', telephone_2: '5565544'})
Distributor.create({company: c, name: 'SUPERSERVITECA CAÑAVERALEJO', address_1: 'CALLE 5 # 56-20', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '5131680', email: 'romanllantas@hotmail.com'})
Distributor.create({company: c, name: 'LLANTAS TULUA', address_1: 'CALLE 26 #31-07', city: 'Tulua', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '2242413', telephone_2: '2253137',email: 'edgar.pena1@telecom.com.co'})
Distributor.create({company: c, name: 'AUTO FARO', address_1: 'CRA. 15 NO. 23-09 TEL.8851583', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '8842927', telephone_2: '8808770'})
Distributor.create({company: c, name: 'CAR SERVICE DEL VALLE LTDA', address_1: 'CRA. 19 CALLE 1 SUR ESQ.', city: 'Buga', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '3164433401', telephone_2: '3003024098'})
Distributor.create({company: c, name: 'SUMAUTO S.A.S.', address_1: 'CALLE 9 # 30-A-21', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '5565490', email: 'almacen@sumauto.net'})
Distributor.create({company: c, name: 'LLANCENTER TUNING', address_1: 'CALLE 13 #67-40', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '3318647', telephone_2: '6829826',email: 'llancentertuning@hotmail.com'})
Distributor.create({company: c, name: 'MAXI RINES S EN CS', address_1: 'CALLE 8 # 27-09', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '5145783'})
Distributor.create({company: c, name: 'MORA OCAMPO EDWARD', address_1: 'CALLE 25 # TRANSV. 25-C-02', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '3352242'})
Distributor.create({company: c, name: 'SUPERSERVICIO L.M.A.', address_1: 'CRA. 53 # 10-42', city: 'Cali', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '3105007647'})
Distributor.create({company: c, name: 'SUPERLLANTAS  DE OCCID', address_1: 'CALLE 10 # 7-31', city: 'Cartago', state: 'Valle del Cauca', country: 'Colombia', telephone_1: '2128803'})
Distributor.all.each do |d|
  d.name = d.name.titleize
  d.address_1 = d.address_1.titleize
  d.address_2 = d.address_2.titleize unless d.address_2.nil?
  d.save
end